# Generated by Django 5.1.2 on 2024-10-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_news', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_zagalovok', models.CharField(max_length=128)),
                ('news', models.CharField(max_length=1024)),
                ('news_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('news_date_time', models.CharField(max_length=32)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novostnoysayt_app.news')),
            ],
        ),
    ]
