# Generated by Django 5.1.2 on 2024-10-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novostnoysayt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsnews',
            name='news_who_write',
            field=models.CharField(default='Неизвестный автор', max_length=64),
            preserve_default=False,
        ),
    ]
