# Generated by Django 5.1.2 on 2024-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novostnoysayt_app', '0002_optionsnews_news_who_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
