# Generated by Django 5.1.2 on 2024-10-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novostnoysayt_app', '0003_news_news_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_photo',
            new_name='new_photo',
        ),
    ]
