# Generated by Django 5.1.2 on 2024-10-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novostnoysayt_app', '0004_rename_news_photo_news_new_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='new_photo',
        ),
    ]
