# Generated by Django 5.1.2 on 2024-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novostnoysayt_app', '0005_remove_news_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsnews',
            name='second_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
